#!/usr/bin/env python

#   Copyright: Chris Cowley 2010
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
# 
# Standard Nagios return codes
OK       = 0
WARNING  = 1
CRITICAL = 2
UNKNOWN  = 3

import sys
import telnetlib
import string, re
import os
from optparse import OptionParser

__author__      = "Chris Cowley"
__title__       = "Nagios plugin to check Dot Hill Revolution Storage Arrays"
__version__     = 0.1


def parseOptions():
    parser = OptionParser()
    parser.add_option("-H", "--host", dest="HOST")
    parser.add_option("-U", "--username", dest="USERNAME")
    parser.add_option("-P", "--password", dest="PASSWORD")
    parser.add_option("-T", "--test", dest="TEST")
    (options, args) = parser.parse_args()

    global host, user, password, test
    host = options.HOST
    user = options.USERNAME
    password = options.PASSWORD
    test = options.TEST

def usage():
    print "Usage: \n"
    print "check_dothill -U <user> -H <host> -P <password> -T disk|vdisk|sensor-status|ports"

def checkSensors():
    error = 0
    tn = telnetlib.Telnet(host)
    tn.read_until("login: ")
    tn.write(user + "\n")
    tn.read_until("Password: ")
    tn.write(password + "\n")
    tn.write("show sensor-status\n")
    tn.write("exit\n")
    output = tn.read_all().split("\r\n")
    for line in output:
        if line.find('Error') != -1:
            error = 1
    return error
                
def checkVdisks():
    error = 0
    tn = telnetlib.Telnet(host)
    tn.read_until("login: ")
    tn.write(user + "\n")
    tn.read_until("Password: ")
    tn.write(password + "\n")
    tn.write("show vdisks\n")
    tn.write("exit\n")
    output = tn.read_all().split("\n")
    for line in output:
        if line.find('Crit') != -1:
            error = 1
    return error

def checkPorts():
    error=0
    tn = telnetlib.Telnet(host)
    tn.read_until("login: ")
    tn.write(user + "\n")
    tn.read_until("Password: ")
    tn.write(password + "\n")
    tn.write("show ports\n")
    tn.write("exit\n")
    output = tn.read_all().split("\n")
    for line in output:
        if line.find('Disconnected') != -1:
            error = error + 1
    return error

def checkDisks():
    error=0
    tn = telnetlib.Telnet(host)
    tn.read_until("login: ")
    tn.write(user + "\n")
    tn.read_until("Password: ")
    tn.write(password + "\n")
    tn.write("set cli-parameters console pager disabled")
    tn.write("show disks\n")
    tn.write("exit\n")
    output = tn.read_all().split("\n")
    for line in output:
        if line.find('OK') != -1:
            error = error + 1
    return error

if __name__ == "__main__":
    parseOptions()
    if test == "sensor-status":
        if checkSensors() == 0:
            print "SENSORS OK"
            sys.exit(0)
        else:    
            print "SENSOR WARNING"
            sys.exit(1)
    elif test == "vdisks":
        if checkVdisks() == 0:
            print "vDisks OK"
            sys.exit(0)
        else:
            print "vDisk WARNING"
            sys.exit(1)

    elif test == "ports":
        if checkPorts() > 3:
            print "FC PORTS CRITICAL: All FC ports are down"
            sys.exit(2)
        elif checkPorts() <= 3 and checkPorts() > 0:
            print "FC PORT WARNING: %d ports are down" % checkPorts()
            sys.exit(1)
        else:
            print "FC PORTS OK"
            sys.exit(0)
            
    elif test == "disks":
        if checkDisks() > 1:
            print "DISK CRITICAL: Multiple disk failures"
            sys.exit(2)
        elif checkDisks() == 1:
            print "Disk WARNING: A disk has failed" 
            sys.exit(1)
        else:
            print "Disks OK"
            sys.exit(0)
    else:
        print "Unknown check! Available checks are:\nvdisks\nsensor-status\nports"
        sys.exit(22)
